Added Chetan-07 to CoP
redhat-cop/org pull request #541
Opened 2022-12-11 04:26 UTC by sabre1041

Added Chetan-07 to CoP to resolve #539

2022-12-11 19:23 UTC, pabrahamsson commented on config.yaml
> +      - Chetan-07
```suggestion
      - chetan-07
```

2022-12-11 19:24 UTC, pabrahamsson requested changes
As per #514 we've moved to using lowercase usernames for consistency. Would you mind updating @sabre1041?

2023-01-13 20:08 UTC, sabre1041 commented
@pabrahamsson updated to lowercase

2023-01-14 03:19 UTC, pabrahamsson approved these changes
LGTM

2023-01-14 03:19 UTC, merged