Update config.yaml
redhat-cop/org pull request #551
Opened 2023-01-24 23:22 UTC by ashokjammula1

New member of babylon and RHPDS team

2023-01-24 23:23 UTC, 9strands commented
Hi, Redhat-cop maintainers, I confirm that @ashokjammula1 is part of my team and will require the same access that I have.  Please approve so that we can get @ashokjammula1 into our workflows and training.  Thank you!

2023-01-24 23:28 UTC, pabrahamsson requested changes
Thank you @ashokjammula1 and thank you @9strands for the confirmation.
This looks good but could you please update the PR to keep the usernames in alphabetical order?

2023-01-25 00:17 UTC, 9strands commented
Hi, @pabrahamsson - yes, I will work with @ashokjammula1 to update and keep alpha order.

2023-01-25 01:11 UTC, 9strands commented
@pabrahamsson - updated, I believe this is as you requested.

2023-01-25 01:59 UTC, pabrahamsson reviewed
Thank you for the update, I left suggested changes inline.

2023-01-25 01:59 UTC, pabrahamsson commented on config.yaml
>            - aleixhub
```suggestion
          - ahsen-shah
          - aleixhub
          - ashokjammula1
```

2023-01-25 01:59 UTC, pabrahamsson commented on config.yaml
>                    - aleixhub
```suggestion
                  - aleixhub
                  - ashokjammula1
```

2023-02-01 14:25 UTC, pabrahamsson approved these changes
LGTM

2023-02-01 14:26 UTC, merged