Ansible ZipShip integration
redhat-cop/org pull request #607
Opened 2023-10-01 06:28 UTC by sabre1041

Creation of repositories and teams for Ansible ZipShip effort

2023-10-01 10:37 UTC, pabrahamsson requested changes

2023-10-01 10:37 UTC, pabrahamsson commented on config.yaml
> +          - brady-s
```suggestion
          - bontreger
          - brady-spiva
```

2023-10-01 13:39 UTC, sabre1041 commented on config.yaml
> +          - brady-s
@pabrahamsson corrected

2023-10-02 12:28 UTC, pabrahamsson commented on config.yaml
> +          - bontreg
I you missed this one @sabre1041 
```suggestion
          - bontreger
```

2023-10-02 16:21 UTC, sabre1041 commented on config.yaml
> +          - bontreg
3rd time is the charm

2023-10-03 02:28 UTC, pabrahamsson commented on config.yaml
> +          - jeffcpu
Maybe this one too @sabre1041? Sorry I missed it before
```suggestion
          - jeffcpullen
```

2023-10-03 02:38 UTC, pabrahamsson approved these changes
LGTM

2023-10-03 02:38 UTC, merged