Adding makirill (Kirill Malgichev)
redhat-cop/org pull request #680
Opened 2024-01-09 23:50 UTC by makirill

Adding Kirill Malgichev to the gpte group

2024-01-10 00:27 UTC, jkupferer approved these changes

2024-01-10 09:05 UTC, garethahealy requested changes
@makirill you need to become a member of the org first
- https://github.com/redhat-cop/org/issues/new?assignees=&labels=access&projects=&template=become-a-contributor.md&title=Please+add+me+as+a+member+of+the+redhat-cop+organization

please follow the instructions in that issue and then update this PR

2024-01-10 09:06 UTC, garethahealy commented
/dont-merge

2024-01-11 13:43 UTC, makirill commented
@garethahealy thank you for the info, I've created issue https://github.com/redhat-cop/org/issues/681

2024-01-11 15:52 UTC, merged